name: chapasdk
description: Chapa flutter library to accept payment via telebirr, CBEBirr, E-birr and m-pessa etc.
version: 0.0.6
homepage: https://github.com/chapa-et/chapa-flutter

environment:
 sdk: '>=3.4.1 <4.0.0'
 flutter: ">=3.4.1"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  flutter_inappwebview: ^6.0.0
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.4
  dio: ^5.4.1
  encrypt: ^5.0.3
  pointycastle: ^3.7.4
  bloc: ^8.1.3
  intl: ^0.19.0
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/images/cbebirr.png
    - assets/images/ebirr.png
    - assets/images/telebirr.png
    - assets/images/ethiopia-flag.png
    - assets/images/mpesa.png
    - assets/images/success-icon.png
    - assets/images/chapa-logo.png
