name: chapasdk
description: Chapa flutter library to accept payment via Card, PayPal, Amole, CBEBirr, AwashBirr and/or telebirr etc.
version: 0.0.6
homepage: https://github.com/chapa-et/chapa-flutter

environment:
 sdk: '>=3.4.1 <4.0.0'
 flutter: ">=3.4.1"

dependencies:
  flutter:
    sdk: flutter

  http: 
  flutter_inappwebview: 6.0.0 
  connectivity_plus: 
  fluttertoast: 
  dio:
  encrypt:
  pointycastle:
  bloc: ^8.1.4
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
